CC=clang -Wall -Werror -std=c++11 

all: bin/parsearch bin/parmerge

bin/parsearch: parsearch.cpp
	$(CC) parsearch.cpp -o bin/parsearch

bin/parmerge: parmerge.cpp
	$(CC) parsearch.cpp -o bin/parmerge
